apiVersion: apps/v1beta1
kind: Deployment
metadata:
  generation: 1
  labels:
    run: nshou-elastic-kibana-deploy-yml
  name: nshou-elastic-kibana-deploy-yml
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nshou-elastic-kibana-deploy-yml
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nshou-elastic-kibana-deploy-yml
    spec:
      containers:
      - image: registry.ng.bluemix.net/wsa-namespace/nshou-elastic-kibana:0.1
        imagePullPolicy: Always
        name: nshou-elastic-kibana-deploy-yml
---
apiVersion: v1
kind: Service
metadata:
  name: nshou-elastic-kibana-deploy-yml
  labels:
    run: nshou-elastic-kibana-deploy-yml
spec:
  selector:
    run: nshou-elastic-kibana-deploy-yml
  ports:
  - protocol: TCP
    port: 5601
    targetPort: 5601
  type: NodePort
